version: "3.3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      VIRTUAL_HOST: mc.mader.lo
      LETSENCRYPT_HOST: mc.mader.xyz
      LETSENCRYPT_EMAIL: vincent.mader@icloud.com

    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./data:/data
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    external: true
    name: proxy_my_awesome_proxy_network # same name as in `./proxy/docker-compose.yml` + prefix (see "docker network ls")

