version: "3.3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      VIRTUAL_HOST: mc.mader.xyz, mc.mader.lo
      LETSENCRYPT_HOST: mc.mader.xyz
      LETSENCRYPT_EMAIL: vincent.mader@icloud.com

    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./data:/data
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    external: true
    name: proxy_mxyz_proxy_network 
    # ^ This has to be the same name as specified in `./proxy/docker-compose.yml`.
    #   Additionally, it it prefixed by the proxy directory name (see "docker network ls").

